#000|Heroes can search here and|find either gold, allies, items|or sages|
#001|Heroes can serach here and|find either gold, items, allies|or sages|
#002|Heroes can search here and|find either gold, allies, items|or sages|
#003|Heroes can search here and|find either gold, items, allies|or sages|
#004|Heroes can search here and|find either items, gold, allies|or sages|
#005|Heroes can search here and|find either gold, allies, items|or sages|
#006|This is the chief temple|of Lurinth, goddess of|elves and the forest|
#007|The Grand Oracle lives far|away over the|Illone Mountains|
#008|This was once the thriving|Selentine port city|of Greyport|
#009|For three thousand years, the|Selentine Emperors have|been buried here|
#010|This ancient stone is said to|bless the crops of|those who touch it|
#011|This red-crstal tower is all that|remains of an|ancient Elven city|
#012|Out in the wilderness, amidst|the orcs, the Druids|built a temple|
#013|These ruins are said to be|teeming with|evil creatures|
#014|The ancient Dwarf King Nirn is|entombed in this|mighty crypt|
#015|Heroes can search here and|find either gold, items, allies|or sages|
#016|This is the tower where the mad|wizard Mirk slipped|into insanity|
#017|The wizards of the Greenlands|once dwelt in|a tower here|
#018|The blue dragon Xanithitol|dwelt here with|its eight children|
#019|This tower once stood guard over|the only bridge|to Bane's Lands|
#020|Molok, the demon of the desert,|was imprisoned here|ages past|
#021|All manner of ghosts are said|to roam the|Halls of Chaos|
#022|The black dragon Vengeance|dwelt here before he|met Lord Bane|
#023|Nev Dolar is also known as|the sinking city|of the Dead Swamp|
#024|Once servicing travellers along|the Knight's Way, the|inn was sacked by giants|
#025|This is where the giant-lord|Horan ruled|the Storm-Kingdom|
#026|This is where the giant-lord|Balnor ruled|the Storm-Kingdom|
#027|This is where generations of|giant-lords are|now buried|
#028|An ancient necromancer once|lived in this|dark tower|
#029|Haviel was once a fair Elven|city, but it was|sacked by dark dwarves|
#030|This ancient monolith is where|Elven burial rites|are performed|
#031|This ancient monolith is where|Elven birth rites|are performed|
#032|A small community of gnomes|once built the|tunnels of Gemhold|
#033|The hills around the Dark|Barrows are said|to be haunted|
#034|This is the only known entrance|to the deserted|Halls of Nirnoth|
#035|This huge monolith is said to be|able to stop orcs|crossing the Mindanuin|
#036|This tower houses an ancient|temple to Ymorgia,|Goddess of Orcs|
#037|The half-ogre tyrant Baal was|buried here|centuries past|
#038|Naar, the Orc-Lord was|entombed here|while still alive|
#039|Little is known of this|ancient stone|monument|
