#000|The eggs of the Blue Dragons|are left here in the cold|to hatch|
#001|These mines were operated|by a group of Dwarves and|join up with the Zhor Mines|
#002|These mines were operated by|a group of kobolds and join|up with the Zhur Mines|
#003|This temple is owned by the|dragon-priest Ruul of|Horncrag|
#004|The city of Sarin was destroyed|by a giant seven-headed|hydra|
#005|The Wyvern Plague of 1934|originated from a colony of|Wyverns in these caves|
#006|A seven-headed hydra once|lived in these|ruins|
#007|This temple is run by the|high dragon-priest Draco, who|is over 2000 years old!|
#008|The family and relatives of the|Golden Lord are all|buried here|
#009|These ancient halls were once|the capital of a race of|Elves|
#010|A wise old hermit was once|rumoured to live|here|
#011|Ruaga the dragon cried here|for 1000 years, creating the|River of Tears|
#012|The eggs of the Red Dragons|are left here in the heat to|incubate|
#013|The dragon Ruaga was|entombed here after mourning|her mate for 1000 years|
#014|The largest troll in the|Dragon Realms, called Urg,|lives in these caves|
#015|From this tall tower, Lord|Silver can survey all of|his lands|
#016|The family and relatives of|Lord Silver are buried|here|
#017|Hidden by forest and hills,|this temple is seldom visited|by anyone|
#018|This temple is run by the|blue dragon-priest Sharil|of the North|
#019|This ancient outpost once|guarded the way to the city|of Beard|
#020|A mad wizard once lived|here, as far from civilization|as he was able to go!|
#021|This ruin was the first casualty|of 1934 DY, as the Wyverns|flew south through the gap!|
#022|This city was ruined in|the Wyvern Plague of|1934 DY|
#023|This city was destroyed in|the Wyvern Plague of|1934 DY|
#024|Hunaz's Tomb is|inhabited by monsters and|full of treasure!|
#025|Ruins of Ilok is|inhabited by monsters and|full of treasure!|
#026|Kirok's Crypt is|inhabited by monsters and|full of treasure!|
#027|Exon's Crypt is|inhabited by monsters and|full of treasure!|
#028|Ruins of Araz is|inhabited by monsters and|full of treasure!|
#029|Volin's Crypt is|inhabited by monsters and|full of treasure!|
#030|Parar's Tomb is|inhabited by monsters and|full of treasure!|
#031|Ruins of Okon is|inhabited by monsters and|full of treasure!|
#032|Ruins of Ok is|inhabited by monsters and|full of treasure!|
#033|Exak's Crypt is|inhabited by monsters and|full of treasure!|
#034|Hunaz's Tower is|inhabited by monsters and|full of treasure!|
#035|Foraz's Tomb is|inhabited by monsters and|full of treasure!|
#036|Ruins of Exak is|inhabited by monsters and|full of treasure!|
#037|Kiror's Tower is|inhabited by monsters and|full of treasure!|
#038|Ruins of Kiror is|inhabited by monsters and|full of treasure!|
#039|Ruins of Kiril is|inhabited by monsters and|full of treasure!|
