#000|The Ancient Temple can bless your|armies or give you|quests|
#001|Ruins of Volil is|inhabited by monsters and|full of treasure!|
#002|Volin's Tomb is|inhabited by monsters and|full of treasure!|
#003|Hunonhold is|inhabited by monsters and|full of treasure!|
#004|Parak's Tomb is|inhabited by monsters and|full of treasure!|
#005|Ruins of Azar is|inhabited by monsters and|full of treasure!|
#006|Ruins of Parar is|inhabited by monsters and|full of treasure!|
#007|Hunin's Tomb is|inhabited by monsters and|full of treasure!|
#008|Ruins of Azin is|inhabited by monsters and|full of treasure!|
#009|Kiraz's Tomb is|inhabited by monsters and|full of treasure!|
#010|Hunaz's Tower is|inhabited by monsters and|full of treasure!|
#011|Azin's Crypt is|inhabited by monsters and|full of treasure!|
#012|Ilil's Tomb is|inhabited by monsters and|full of treasure!|
#013|Exon's Tomb is|inhabited by monsters and|full of treasure!|
#014|Volonhold is|inhabited by monsters and|full of treasure!|
#015|The Hidden Temple can bless your|armies or give you|quests|
#016|Parin's Tower is|inhabited by monsters and|full of treasure!|
#017|Ruins of Hunil is|inhabited by monsters and|full of treasure!|
#018|Kirorhold is|inhabited by monsters and|full of treasure!|
#019|Kirok's Tower is|inhabited by monsters and|full of treasure!|
#020|The Ancient Temple can bless your|armies or give you|quests|
#021|Pararhold is|inhabited by monsters and|full of treasure!|
#022|Foraz's Tower is|inhabited by monsters and|full of treasure!|
#023|Volok's Tomb is|inhabited by monsters and|full of treasure!|
#024|Ar's Tower is|inhabited by monsters and|full of treasure!|
#025|Hunhold is|inhabited by monsters and|full of treasure!|
#026|Ruins of Volon is|inhabited by monsters and|full of treasure!|
#027|Parar's Tower is|inhabited by monsters and|full of treasure!|
#028|Paril's Tower is|inhabited by monsters and|full of treasure!|
#029|Ruins of Okak is|inhabited by monsters and|full of treasure!|
#030|Parhold is|inhabited by monsters and|full of treasure!|
#031|Ruins of Araz is|inhabited by monsters and|full of treasure!|
#032|Exil's Tower is|inhabited by monsters and|full of treasure!|
#033|Arilhold is|inhabited by monsters and|full of treasure!|
#034|Ruins of Il is|inhabited by monsters and|full of treasure!|
#035|The High Temple can bless your|armies or give you|quests|
#036|Aror's Tower is|inhabited by monsters and|full of treasure!|
#037|Arhold is|inhabited by monsters and|full of treasure!|
#038|Volor's Tomb is|inhabited by monsters and|full of treasure!|
#039|Forak's Tomb is|inhabited by monsters and|full of treasure!|
