#000|A seer once lived here.|It is said that one can see the|edge of the world from here!|
#001|The Weeping God of|Tierremar has lived in this|tower for 1000 years|
#002|Usurus, the Weeping God's|child lived here before he was|slain by Arus of Felinor|
#003|The Felinian hero Arus lived here|before the Weeping God|slew him|
#004|This unholy site is the main|temple of Dark Lady,|Zhoragh the Unholy|
#005|The huge and powerful troll,|Zok, is rumoured to live in|this labyrinth of tunnels|
#006|An outpost of Gnoles lived|here before the Dwarves hunted|them down.|
#007|This is the place of worship|for the Elves of Aspenhome,|Champions of Light!|
#008|A powerful goblin-mage|once made his home|here|
#009|The Marcanian city of|Meerax was sacked by|the Giants|
#010|This monument is imbued with|some strange power of|Zhoraghians|
#011|This was once a thriving|Felinorian|city|
#012|A group of kobolds lives|in these twisted|passageways|
#013|This long-deserted tower|stands watch over the|Bay of Betrayal|
#014|This was once a mighty|Felinorian|stronghold|
#015|This maze is one of the|tests which Twenorian Mages|must pass|
#016|A band of trolls once lived|in this keep, but the Dwarves|killed them|
#017|Negrimor the Lich, who was|murdered by his lover, Zhoragh,|rests here|
#018|This was once a keep|of the Stone|Giants|
#019|The Mercanians once built|a keep here, but the Giants|sacked it|
#020|An ancient druid once watched|over the Wild Coast|from here|
#021|There was once a Felinorian|mining operation|here|
#022|This tower once guarded|the entrance to|Aspenhome|
#023|This tower once guarded|the entrance to|Aspenhome|
#024|This is the Temple of the|Mercanian God, Okradon - |God of Wealth!|
#025|The Trelarian Monks once|watched the Blood Ogres|from this tower|
#026|An ancient Elvish city|rumoured to lie underground|here|
#027|The old keep of Tharbro|was once situated here - |before the Dwarves burnt it!|
#028|This altar to a forgotten|God is said to be|haunted|
#029|The Blood Ogres burnt down|this Mercanian attempt at|a trading outpost|
#030|This giant marble block is|regarded with holy|reverance by the Knights|
#031|The Blood Ogres burnt down|the Mercanians attempt at a|trading outpost|
#032|The keep of Thuril|was sacked by the|Blood Ogres|
#033|Nobody knows who or what|built this ancient|tower|
#034|These ruins are|all that remain of an ancient|Dwarven Mine|
#035|The old city of Eldakkar|was once built here, but|the Knights razed it|
#036|This shrine is dedicated|to the Horse God|of Mount Equus|
#037|This is the worship place of|the Cloud Knights of|the Isle of Winds|
#038|Every Ogre-King is|brought here and entombed|when he dies|
#039|This Knightly monument|commemorates an ancient|war with the dark Dwarves|
