#000|This temple is tended by|100 Priestesses of the Moon|Goddess, Aluna|
#001|An old wizard once lived here|and sold potions to|passers-by|
#002|The Great Unicorn lives|here by Eye|Lake|
#003|Strange fiery creatures are|said to live in these|halls|
#004|In this stone circle, Unicorns|gather to exchange|stories|
#005|A black dragon once lived|in these|caves|
#006|The magicians meet in this|secret hall every time the|moon is a crescent|
#007|This tower houses a smaller|version of the Great|Orb|
#008|This is the tallest structure|in the Isles of|Sorcery|
#009|This tower houses a smaller|version of the Great|Orb|
#010|This ruin is the home of many|unsavoury creatures from|the netherworld|
#011|Azg, the first necromancer,|was buried here 1000 years|ago|
#012|This rough windswept hall|is most likely empty|now|
#013|This temple is tended by|100 Warrior-Priests of|the Sun God, Sol|
#014|This ruin is inhabited by the|foul creatures used by the|necromancers|
#015|An old man here once taught|the summoners the art of|scribing magical stars|
#016|This is the tower where the mad|wizard Mirk slipped|into insanity|
#017|The wizards of the Greenlands|once dwelt in|a tower here|
#018|The blue dragon Xanithitol|dwelt here with|its eight children|
#019|This tower once stood guard over|the only bridge|to Bane's Lands|
#020|Molok, the demon of the desert,|was imprisoned here|ages past|
#021|All manner of ghosts are said|to roam the|Halls of Chaos|
#022|The black dragon Vengeance|dwelt here before he|met Lord Bane|
#023|Nev Dolar is also known as|the sinking city|of the Dead Swamp|
#024|Once servicing travellers along|the Knight's Way, the|inn was sacked by giants|
#025|This is where the giant-lord|Horan ruled|the Storm-Kingdom|
#026|This is where the giant-lord|Balnor ruled|the Storm-Kingdom|
#027|This is where generations of|giant-lords are|now buried|
#028|An ancient necromancer once|lived in this|dark tower|
#029|Haviel was once a fair Elven|city, but it was|sacked by dark dwarves|
#030|This ancient monolith is where|Elven burial rites|are performed|
#031|This ancient monolith is where|Elven birth rites|are performed|
#032|A small community of gnomes|once built the|tunnels of Gemhold|
#033|The hills around the Dark|Barrows are said|to be haunted|
#034|This is the only known entrance|to the deserted|Halls of Nirnoth|
#035|This huge monolith is said to be|able to stop orcs|crossing the Mindanuin|
#036|This tower houses an ancient|temple to Ymorgia,|Goddess of Orcs|
#037|The half-ogre tyrant Baal was|buried here|centuries past|
#038|Naar, the Orc-Lord was|entombed here|while still alive|
#039|Little is known of this|ancient stone|monument|
