#000|This is a temple to Azaral,|lord of death and patron of|all liches|
#001|The God of the Isle of the Pit|lives deep in the ground|here|
#002|These ruins were the original|site of the city of Marspray|before it was razed|
#003|In a hillock, in the marsh,|the Old Cave is full of|monsters and treasure|
#004|This statue commemmorates|the great battle of|the marsh|
#005|This tower represents the|falling darkness of|night|
#006|This tower represents the|unlight - the pre-dawn|light|
#007|The ancient Sirian hero,|Vallandar, was buried here|2000 years ago|
#008|This ancient site of Gwindhor|is now long|overgrown by the forest|
#009|This tower once housed the|Knights of Larga who guarded|the Gap of Larga|
#010|These caves are said to|be where dragons come to|die|
#011|This was once part of|a signalling system of the|Horse Tribes|
#012|Many thousands of bodies|are buried in this|graveyard|
#013|Ushmak the Goblin-lord|once lived in|this tower|
#014|It was rumoured that a|Unicorn once surveyed the|lands from here|
#015|This is the temple to|Iris, patron goddess of the|Middle Kingdoms|
#016|This was once part of a|sinalling system between the|Horse Tribes|
#017|An ancient oracle once lived|here, deep within the|Marsh of Reason|
#018|In ages past, this tower|guarded the southern entrance|to the Doomlands|
#019|The Elftower was once|the home of the ancient|hero Eldaron|
#020|This is the temple|of the Dark|Elves|
#021|This is the final resting place|of Morphius, the first and last|ruler of the dead city|
#022|An ogre-mage rules|this long-abandoned|ruin|
#023|This was once part of a|signalling system used by|the Horse Tribes|
#024|An ancient mage, reputed|to study human nature, once|lived here|
#025|A huge black stone marks the|centre of activity for|Glanir's ghosts|
#026|A great battle was fought here|between the Brill tribe and a|group of Goblins|
#027|Ulric, the world's greatest|summoner once lived|here|
#028|Dead goblin warriors are|taken and buried|here|
#029|It is said the world's oldest|unicorn lives|here|
#030|This giant marble block is|regarded with holy|awe by the Giants|
#031|The Giants burnt down this|city after its leader insulted|them|
#032|The Sirians recently sacked|this city of|orcs|
#033|A strange water spirit once|inhabited these|ruins|
#034|These pits hold many foul|and vicious|creatures|
#035|This is a temple to|Ymorgia, Goddess of|the Ussyrian Orcs|
#036|An ancient troll named|Bulog is said to live deep in|these caves|
#037|An elven archmage lived here|before one of his experiments|went horribly wrong|
#038|This is the ruin of|a dwarven mine named|Grimhold|
#039|Mages are required to take|a test in this tower before|they graduate|
