#000|These ruins were once|a citadel of the|Dream Knights|
#001|These ruins were once an|outpost of the|Dream Knights|
#002|No searcher has ever found|the bottom of this|chasm|
#003|This is where the Dream|Knights come to|worship|
#004|Nobody is sure what these|ancients stones|are for|
#005|An ancient pegasus is|said to live in these|ruins|
#006|All manner of monsters|are said to roam these|rich halls|
#007|This magical stone is said to|grant gold to those who|reach it|
#008|Here the Lord of Nighmares|can survey the Land|of Greed|
#009|This tower overlooks the|pass into the Lands|of Nightmare|
#010|Set deep in the mountains,|this temple is home to|the Lord of Flight|
#011|Creatures from the Lands of|Flight occasionally nest|here|
#012|The caverns here are deep|and full of dreadful|beasts|
#013|A family of griffons once|nested in this ruined|tower|
#014|This stone grants the deepest|desire of those|who touch it|
#015|Treasures uncounted are|rumoured to lie in|these halls|
#016|This ancient ruined citadel|is home to many strange|monsters|
#017|This monolith marks pass|to the much despised Lands|of Beauty|
#018|These dungeons are populated|with the true creatures|of Nightmare|
#019|This tower watches over|the two bridges into the|Land of Flight|
#020|This tower was the home of|the Faerie-Lord|Amethesius|
#021|The minotaurs of Bulldar|bury their folk|here|
#022|A spring in these caverns|feeds the mighty River|of Silver|
#023|The fair city of Oldport|was sacked by the Lord of|Power|
#024|This tower was the home of|the Faerie-Lord|Crystallus|
#025|These caverns were|discovered by the|adventurer, Jariz|
#026|This tower was the home|of the Faerie-Lord|Emeralus|
#027|This ruined tower is|surrounded by a crescent|of hills|
#028|This is the home of the|Lord of|Beauty|
#029|The lonely Dragon of Dreams|once lived in this ancient|ruin|
#030|This tower watches|over|Fire Bay|
#031|This magical red stone is|said to open doorways to|strange lands|
#032|This ruin marks the border|of the Lands of|Sloth|
#033|This is the where the|Lord of Fire draws his|power from|
#034|These ruins were burnt to|the ground by an experiment|of the Lord of Fire|
#035|This disgusting ruin has|mostly collapsed into the|marsh|
#036|The important folk of the|lands of fire are cremated|here|
#037|This was once a city|owned by the|giants|
#038|The Lords of Fire are|all cremated|here|
#039|The wizard of Point once|lived in this tall red|tower|
